name: Windows Build

env:
  R2V: 6.0.7

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-windows:
    name: Build for Windows with MSVC
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.x

      - name: Prepare MSVC toolchain
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install dependencies
        shell: bash
        run: |
          pip install meson ninja wget
          choco install wget

      - name: Download Radare2 release
        shell: bash
        run: |
          python -m wget https://github.com/radareorg/radare2/releases/download/${{env.R2V}}/radare2-${{env.R2V}}-w64.zip -o r2.zip
          unzip r2.zip
          mv radare2-${{env.R2V}}-w64 radare2 || mv radare2-w64-${{env.R2V}} radare2
          cp -f radare2/include/libr/r_util/r_event.h radare2/include/libr/r_event.h || true

      - name: Build with Meson
        shell: cmd
        run: |
          meson setup builddir -Dprefix=%cd%\install
          meson compile -C builddir
          meson install -C builddir

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: builddir\install\**\*
